import { Montserrat,  } from "next/font/google";
import "../styles/globals.css";
import localFont from 'next/font/local'
const monts = Montserrat({ subsets: ["latin"], weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"], variable: "--font-montserrat" });

const proto = localFont(
  {
    src: [
      {
        path: '../assets/font/ProtestRiot-Regular.ttf',
        weight: '400',
        style: 'normal',
      },
    ],
    variable: "--font-proto",
  }
)

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${monts.className} `}>{children}</body>
    </html>
  );
}
